[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 2

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = []
git-fetch-with-cli = false

[licenses]
allow = ["MIT"]
confidence-threshold = 0.9
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "warn"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
